#!/bin/bash

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker-compose down
docker-compose build

tar -C .. -czvf flexo-server/flexo.tar.gz flexo/src flexo/Cargo.toml
cp flexo-server/flexo.tar.gz flexo-server-slow-primary/

/usr/bin/docker-compose build || exit 1
/usr/bin/docker-compose up --exit-code-from flexo-client
