#!/bin/bash

set -o pipefail

echo "FLEXO_TEST_MODE=$FLEXO_TEST_MODE"

export RUST_BACKTRACE=full
export RUST_LOG=debug

if [ "$FLEXO_TEST_MODE" = 'INTEGRATION_TEST' ]; then
  # Wait a moment until all servers have started.
  sleep 3

  exec /usr/bin/integration-test-client
else
  # If INTEGRATION_TEST has not been specified, then we just keep all containers running with the following statement:
  tail -f /dev/null
  # This can be useful to just interactively run commands inside the various docker containers and try things out
  # or troubleshoot issues.
fi
