#!/bin/bash

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker-compose down

tar -C ../../ -czvf flexo-server/flexo.tar.gz flexo/src flexo/Cargo.toml flexo/Cargo.lock
cp flexo-server/flexo.tar.gz flexo-server-slow-primary/
cp flexo-server/flexo.tar.gz flexo-server-delay-primary/
cp flexo-server/flexo.tar.gz flexo-server-no-content-length-primary/
cp flexo-server/flexo.tar.gz flexo-server-fast/
cp flexo-server/flexo.tar.gz flexo-server-mirror-stalling/
cp flexo-server/flexo.tar.gz flexo-server-redirect/
cp flexo-server/flexo.tar.gz flexo-server-mirror-stalling-after-header

tar -C .. -czvf flexo-server-delay/tcp-proxy-delay.tar.gz tcp-proxy-delay/src tcp-proxy-delay/Cargo.toml
cp flexo-server-delay/tcp-proxy-delay.tar.gz mirror-delay-mock/

tar -C .. -czvf flexo-client/integration-test-client.tar.gz \
    integration-test-client/src/main.rs \
    integration-test-client/src/http_client.rs \
    integration-test-client/Cargo.toml

/usr/bin/docker-compose build || exit 1
/usr/bin/docker-compose up --exit-code-from flexo-client
