#!/bin/bash

docker-compose down

cd ../flexo || exit 1
PKG_CONFIG_ALLOW_CROSS=1 /usr/bin/cargo build --target=x86_64-unknown-linux-musl || exit 1
cd "$OLDPWD" || exit 1
cp ../flexo/target/x86_64-unknown-linux-musl/debug/flexo ./flexo-server || exit 1
/usr/bin/docker-compose build || exit 1
/usr/bin/docker-compose up
