#!/bin/bash

function fail_and_exit() {
  printf "%-50s %s\n" "$TESTCASE" "[FAILURE]"
  exit 1
}

function print_success() {
  printf "%-50s %s\n" "$TESTCASE" "[SUCCESS]"
}

function clear_pacman_cache() {
  mv /var/cache/pacman/pkg/* /tmp/verified || fail_and_exit
}

cd /tmp || exit 1

mkdir /tmp/verified || exit 1

# Wait for the flexo server to start and finish the mirror selection process.
sleep 5

## ==============================================================================================================
TESTCASE='flexo-test-persistent-connections-c2s'
# Connections made from client-to-server (i.e., from pacman to flexo) should be persistent.
## ==============================================================================================================
/usr/bin/tcpdump -i lo 'tcp[tcpflags] & tcp-syn != 0' 2>/tmp/tcpdump-syn &
TCPDUMP_PID=$!
clear_pacman_cache

sleep .1

# There's no particular reason why we chose those packages, we just selected a few arbitrary packages that are small
# and have no dependencies.
/usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly rxvt-unicode-terminfo lostfiles  perl-file-path-expand || fail_and_exit

sleep .1

kill $TCPDUMP_PID || fail_and_exit

if grep -q '2 packets captured' /tmp/tcpdump-syn; then
  # Expect only a single connection to be established, so we should have 2 SYN packets: One from pacman to flexo,
  # and a second one from flexo to pacman.
  print_success
else
  fail_and_exit
fi

# ===============================================================================================================
TESTCASE='flexo-test-install'
## Install a few packages via pacman. Using pacman (instead of just downloading the package via wget or curl)
## ensures that the file served by flexo is identical to the file from the remote mirror. This is due to the fact
## that pacman uses gpg signatures for verification.
## ==============================================================================================================

if /usr/bin/pacman -Sy --noconfirm --noprogressbar mozilla-common java-environment-common fuse-common; then
  print_success
else
  fail_and_exit
fi

# Clear the pacman cache: We intend to simulate the situation where the package is cached by the flexo server,
# but not by the client that connects to the flexo server.
clean_pacman_cache

## ==============================================================================================================
TESTCASE='flexo-test-persistent-connections-s2s'
# Connections made from server-to-server (i.e., from flexo to the remote mirror) should be persistent.
## ==============================================================================================================

/usr/bin/tcpdump -i eth0 'tcp[tcpflags] & tcp-syn != 0' 2>/tmp/tcpdump-syn &
TCPDUMP_PID=$!
clear_pacman_cache

# There's no particular reason why we chose those packages, we just selected a few arbitrary packages that are small
# and have no dependencies.
/usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly pambase dnssec-anchors hyphen-it realtime-privileges || fail_and_exit

kill $TCPDUMP_PID || fail_and_exit

if grep -q '0 packets captured' /tmp/tcpdump-syn; then
  # We assume that since we have already established a connection to the remote mirror, no new connection
  # will we established and therefore, no new SYN packets are sent or received.
  print_success
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-install-cached'
## Now that we have a package in flexo's cache, we install this package from the cache.
## ==============================================================================================================

# Reinstall pambase, which has already been downloaded before and should therefore reside in cache.
if /usr/bin/pacman -Sy --noconfirm pambase; then
  print_success
else
  fail_and_exit
fi

clear_pacman_cache

## ==============================================================================================================
TESTCASE='flexo-test-download-cached-concurrently'
## Download the cached package multiple times, concurrently.
## ==============================================================================================================

PACKAGE='pambase'
DOWNLOAD_PATH=$(pacman -Sp $PACKAGE)
if [[ -n $DOWNLOAD_PATH ]]; then
  seq 0 9 | parallel /usr/bin/wget -q "$DOWNLOAD_PATH" -O $PACKAGE-{}
  VERIFIED_FILE=$(/usr/bin/find /tmp/verified -type f -name '*pambase*')
  echo "$VERIFIED_FILE"
  for i in {0..9}; do
    # Files in /var/cache/pacman/pkg have been installed by pacman, and pacman verifies the content all
    # downloaded files. We can therefore assume that if a file downloaded by wget matches the file in
    # /var/cache/pacman/pkg, it has correctly been downloaded.
    if ! /usr/bin/cmp -s "$PACKAGE-$i" "$VERIFIED_FILE"; then
      echo "Files do not match: PACKAGE-$i and $VERIFIED_FILE"
      fail_and_exit
    fi
  done
else
  fail_and_exit
fi
print_success

## ==============================================================================================================
TESTCASE='flexo-test-download-concurrently'
## Download the same uncached packages multiple times, concurrently.
## ==============================================================================================================

PACKAGE='libco'
DOWNLOAD_PATH=$(/usr/bin/pacman -Sp $PACKAGE)
if [[ -n $DOWNLOAD_PATH ]]; then
  seq 0 3 | parallel /usr/bin/wget -q "$DOWNLOAD_PATH" -O $PACKAGE-{}
  # We now download the package because installing packages with pacman also verifies the payload.
  # This allows us to then check if the previous 10 downloads match the verified payload.
  /usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly $PACKAGE || fail_and_exit
  VERIFIED_FILE=$(/usr/bin/find /var/cache/pacman/pkg -type f -name '*libco*')
  for i in {0..3}; do
    if ! /usr/bin/cmp -s "$PACKAGE-$i" "$VERIFIED_FILE"; then
      echo "Files do not match: $PACKAGE-$i and $VERIFIED_FILE"
      fail_and_exit
    fi
  done
  print_success
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-range-cached'
## Use HTTP range requests to skip the first few bytes of a file. The file is already cached by flexo.
## ==============================================================================================================

# No particular reason why we chose lostfiles – just an arbitrary package that has already been downloaded.
DOWNLOAD_PATH=$(/usr/bin/pacman -Sp lostfiles | grep lostfiles)
if [[ -n $DOWNLOAD_PATH ]]; then
  echo "Downloading $DOWNLOAD_PATH"
  curl "$DOWNLOAD_PATH" -H "Range: bytes=1024-" >/tmp/lostfiles-partial-downloaded || fail_and_exit
  if ! /usr/bin/cmp -s --ignore-initial=1024:0 /tmp/verified/lostfiles* /tmp/lostfiles-partial-downloaded; then
    echo "Files do not match: /tmp/lostfiles-partial and /tmp/lostfiles-partial-downloaded"
    fail_and_exit
  else
    print_success
  fi
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-range-non-cached'
## Use HTTP range requests to skip the first few bytes of a file. The file is not cached by flexo.
## ==============================================================================================================

# No particular reason why we chose the 'corkscrew' package – just an arbitrary package that has not been downloaded yet.
PACKAGE='corkscrew'
DOWNLOAD_URL=$(/usr/bin/pacman -Sp $PACKAGE)
if [[ -n $DOWNLOAD_URL ]]; then
  echo "Downloading $DOWNLOAD_URL"
  curl "$DOWNLOAD_URL" -L -H "Range: bytes=1024-" >/tmp/$PACKAGE-partial-downloaded || fail_and_exit
  /usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly --nodeps $PACKAGE || fail_and_exit
  VERIFIED_FILE=$(/usr/bin/find /var/cache/pacman/pkg -type f -name 'corkscrew-*.zst')
  if [[ -n $VERIFIED_FILE ]]; then
    if ! /usr/bin/cmp -s --ignore-initial=1024:0 "$VERIFIED_FILE" /tmp/$PACKAGE-partial-downloaded; then
      echo "Files do not match: $VERIFIED_FILE and /tmp/file-partial-downloaded"
      fail_and_exit
    else
      print_success
    fi
  else
    fail_and_exit
  fi
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-resume-after-abort'
## Start a download, then abort it, then restart the download.
## ==============================================================================================================
PACKAGE='icmake'
/usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly --nodeps $PACKAGE &
PACMAN_PID=$!
sleep 0.75
kill "$PACMAN_PID"
sleep 0.75 # Wait a bit for flexo to detect that the socket has been closed.
rm /var/lib/pacman/db.lck
if /usr/bin/pacman -S --noconfirm --noprogressbar --downloadonly --nodeps $PACKAGE; then
  print_success
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-concurrent-download-non-blocking'
# Downloading a larger file does not stop another client from obtaining a small file quickly.
## ==============================================================================================================
# First, we start downloading a relatively large file:
LARGE_PACKAGE='hyperfine'
DOWNLOAD_PATH=$(pacman -Sp $LARGE_PACKAGE)
/usr/bin/wget -q "$DOWNLOAD_PATH" -O /dev/null &
WGET_PID=$!
# Next, we download a smaller package:
SMALL_PACKAGE='libguess'
DOWNLOAD_PATH=$(pacman -Sp $SMALL_PACKAGE)
/usr/bin/wget -q "$DOWNLOAD_PATH" -O /dev/null || fail_and_exit
# The download of the second package should have completed before the first download.
if ps -p $WGET_PID >/dev/null; then
  print_success
else
  fail_and_exit
fi

## ==============================================================================================================
TESTCASE='flexo-test-download-after-404'
# Attempting to download a file that does not exist does not crash flexo.
## ==============================================================================================================
HTTP_STATUS=$(/usr/bin/curl -o /dev/null --silent --write-out '%{http_code}\n' http://flexo-server:7878/non_existing_file)
if [ "$HTTP_STATUS" != '404' ]; then
  fail_and_exit
fi
PACKAGE='cpuburn'
DOWNLOAD_PATH=$(pacman -Sp $PACKAGE)
# Successfully downloading a file after having obtained a 404 is taken as proof that flexo has not crashed.
if /usr/bin/wget -q "$DOWNLOAD_PATH" -O /dev/null; then
  print_success
else
  fail_and_exit
fi
